# 20250211.3 • Updated YAML for Diagnostic Settings Pipeline

trigger:
  branches:
    include:
      - main

pool:
  vmImage: "windows-latest"

steps:
  - checkout: self
    ref: main # Explicitly checkout the main branch

  - task: AzurePowerShell@5
    displayName: "Run Diagnostic Settings PowerShell Script"
    inputs:
      azureSubscription: "FreeTrial" # Replace with your actual Azure service connection name.
      ScriptPath: "scripts/Detect-Diagnostic-Settings.ps1" # Adjust the path if necessary.
      azurePowerShellVersion: "LatestVersion"
