# 20250211.3 • Updated YAML for Diagnostic Settings Pipeline
# File location: workflows/DiagnosticSettings.yml

trigger:
  branches:
    include:
      - main

pool:
  vmImage: "windows-latest"

steps:
  - checkout: self

  - task: AzurePowerShell@5
    displayName: "Run Diagnostic Settings PowerShell Script"
    inputs:
      azureSubscription: "Free Trial"
      ScriptPath: "scripts/Detect-Diagnostic-Settings.ps1" # Path relative to the repository root.
      azurePowerShellVersion: "LatestVersion"
