# Build Name format
name: $(TeamProject)_$(BuildDefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

# Variables
variables:
  AgentPool: "windows-latest"
  service_connection: "ARM - TSE AZ Management Group"

# Trigger (Manual)
trigger: none

# Stages
stages:
  - stage: Create_Diagnostic_Settings_Json
    displayName: "Create Diagnostic Settings Json"

    jobs:
      - job: CreateDiagnosticSettingsJson
        displayName: "Execute Diagnostic Settings Script"
        pool:
          vmImage: $(AgentPool)

        steps:
          - checkout: self # Ensures the repo is available on the agent

          # Run the PowerShell script
          - task: AzurePowerShell@5
            displayName: "Run Diagnostic Settings Script"
            inputs:
              azureSubscription: $(service_connection)
              ScriptPath: "$(Build.SourcesDirectory)/Detect-Diagnostic-Settings.ps1"
              azurePowerShellVersion: LatestVersion
              ScriptType: FilePath
              errorActionPreference: "Stop"
