name: Deploy to Azure # Name of the workflow

on:
  push:
    branches:
      - main # Runs when pushing to the main branch

jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # Correct syntax for checking out code

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Run PowerShell Script
        shell: pwsh
        run: |
          .\scripts\Detect-Diagnostic-Settings.ps1
